language: cpp
sudo: required
dist: bionic
addons:
  apt:
    sources:
    - sourceline: 'ppa:beineri/opt-qt-5.12.3-bionic'
    packages:
    - qt512-meta-full
    - libgl1-mesa-dev
before_install:
  - sudo apt-get remove -y cmake
  - mkdir cmakebuild
  - cd cmakebuild
  - curl -sSL https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-x86_64.sh -o ./cmake-install.sh
  - chmod +x ./cmake-install.sh
  - sudo ./cmake-install.sh --prefix=/usr/local --skip-license
  - cd ..
  - source /opt/qt512/bin/qt512-env.sh
compiler: g++
script:
  - cmake --version
  - qmake --version
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - make test
