language: cpp
sudo: required
dist: bionic
addons:
  apt:
    sources:
    - sourceline: 'ppa:beineri/opt-qt-5.14.2-bionic'
    packages:
    - qt514-meta-full
    - libgl1-mesa-dev
before_install:
  - sudo apt-get remove -y cmake
  - mkdir cmakebuild
  - cd cmakebuild
  - curl -sSL https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-x86_64.sh -o ./cmake-install.sh
  - chmod +x ./cmake-install.sh
  - sudo ./cmake-install.sh --prefix=/usr/local --skip-license
  - cd ..
  - source /opt/qt514/bin/qt514-env.sh
compiler: g++
script:
  - /usr/local/bin/cmake --version
  - qmake --version
  - mkdir build
  - cd build
  - mkdir server
  - cd server
  - /usr/local/bin/cmake ../..
  - /usr/local/bin/cmake --build .
  - cd ..
  - mkdir client
  - cd client
  - /usr/local/bin/cmake -D_HRP_BUILD_SERVER=OFF ../..
  - /usr/local/bin/cmake --build .
  - cd ..
  - cd ..
after_success:
  - cd build/server
  - cpack
  - cd ../../build/client
  - cpack
