language: cpp
sudo: required
dist: bionic
addons:
  apt:
    sources:
    - sourceline: 'ppa:beineri/opt-qt-5.12.3-bionic'
    packages:
    - qt512-meta-full
    - libgl1-mesa-dev
before_install:
  - source /opt/qt512/bin/qt512-env.sh
  - mkdir cmakebuild
  - cd cmakebuild
  - curl -sSL https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.sh -o ./cmake-install.sh
  - chmod +x ./cmake-install.sh
  - ./cmake-install.sh --prefix=/usr/local --skip-license
  - cd ..
compiler: g++
script:
  - qmake --version
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - make test
